name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
env:
  FORGE_EMAIL: ${{ secrets.FORGE_EMAIL }}
  FORGE_API_TOKEN: ${{ secrets.FORGE_API_TOKEN }}
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: npm install 
        run: |
          cd ${{ github.workspace }} && npm install
      - run: cd static/hello-world && npm install
      - run: cd static/hello-world && npm run build
      - run: npm install --global @forge/cli
      - run: forge settings set usage-analytics true
      - run: forge deploy -e production